### ISSUE TITLE
Exception Handling for "BadStatusLine"

### ISSUE THREAD

**Issue by jandersson** [Moss88/brewMonitor#9]
Traceback (most recent call last):
  File "thermoAcq.py", line 32, in <module>
    response = http_conn.getresponse()
  File "/usr/lib/python3.2/http/client.py", line 1052, in getresponse
    response.begin()
  File "/usr/lib/python3.2/http/client.py", line 346, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.2/http/client.py", line 316, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

**Comment by jandersson** [comment]
Happens when the router does its nightly reset i believe.
